name: devsecops end to end pipeline

on:
    push:
        branches: [main]

jobs:
    code-quality:
        uses: ./.github/workflows/code-qualtity.yml

    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml
    
    docker-scan:
        uses: ./.github/workflows/docker-lint.yml

        # builds nce the security checks are passed
    build:
        needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

    trivy-scan:
        needs: build
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

    deploy:
        uses: ./.github/workflows/deploy-to-server.yml
        secrets: inherit