name: docker secrets

on:
  workflow_dispatch:

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: use docker secrets
        env:
          DOCKER_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "Docker username is $DOCKERHUB_USERNAME"
          echo "Logging into Docker"